---
name: main

on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install poetry==1.3.2
      - name: cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install
      - name: static analysis
        run: |
          poetry run black --check plio tests
          poetry run mypy
      - name: run tests
        run: |
          poetry run pytest
