name: main

on:
  push:
    branches: [$default-branch]
  pull_request: {}
  workflow_dispatch:

jobs:
  main:
    strategy:
      matrix:
        python-version: [3.9, 3.10]
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install poetry
        run: pip install poetry==1.3.2
      - name: cache venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install
      - name: static analysis
        run: |
          poetry run black --check src tests
          poetry run mypy
      - name: run tests
        run: |
          poetry run pytest
