---
# Simple workflow for deploying static content to GitHub Pages
name: pages

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install poetry
        run: pip install poetry==1.3.2 pdoc3
      - name: run pdoc
        run: poetry run pdoc3 --html plio
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
